version: "3.9"
services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    links:
      - redis
      - comments
    environment:
      - PORT=3000
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
  comments:
    build: ./comments
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
  redis:
    image: redis
    ports:
      - "6379:6379"
