version: "3.9"
services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "3000:3000"
    links:
      - redis
      - comments
    environment:
      - PORT=3000
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - SERVICE_COMMENTS_ADDR=comments:3001
  comments:
    build:
      context: .
      dockerfile: ./comments/Dockerfile
    ports:
      - "3001:3001"
    links:
      - redis
    environment:
      - PORT=3001
      - REDIS_ADDR=redis:6379
  redis:
    image: redis
    ports:
      - "6379:6379"
