// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateShowInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	UserID      string  `json:"userId"`
}

type CreateShowPayload struct {
	Show *Show `json:"show"`
}

type CreateUserInput struct {
	Username string `json:"username"`
}

type CreateUserPayload struct {
	User *User `json:"user"`
}
